### ISSUE TITLE
setBadge(0) not working

### ISSUE THREAD

**Issue by shalonteoh** [brozot/Laravel-FCM#112] opened 2018-06-12 02:06 UTC
set badge number to zero is not working but other numbers it's working. What did I do wrong?

        `
        $optionBuilder = new OptionsBuilder();
        $optionBuilder->setTimeToLive(60 * 20);
        $optionBuilder->setContentAvailable(1);
        $notificationBuilder = new PayloadNotificationBuilder();
        $notificationBuilder->setBadge(0);

        $option = $optionBuilder->build();
        $notification = $notificationBuilder->build();

        $downstreamResponse = FCM::sendTo($tokens, $option, $notification);
        `

**Comment by shalonteoh** [comment] 2018-06-12 02:12
The other way around I'm using curl to make POST request to Firebase.

`$url = 'https://fcm.googleapis.com/fcm/send';

    $fields = array (
            'registration_ids' => array (
                    $id
            ),
            'data' => array (
                    "message" => $message
            )
    );
    $fields = json_encode ( $fields );

    $headers = array (
            'Authorization: key=' . "YOUR_KEY_HERE",
            'Content-Type: application/json'
    );

    $ch = curl_init ();
    curl_setopt ( $ch, CURLOPT_URL, $url );
    curl_setopt ( $ch, CURLOPT_POST, true );
    curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
    curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
    curl_setopt ( $ch, CURLOPT_POSTFIELDS, $fields );

    $result = curl_exec ( $ch );
    echo $result;
    curl_close ( $ch );`

**Comment by finalgamer** [comment] 2018-09-17 14:33
This is caused by `array_filter($notification)` which removes array elements that are false or empty **or 0**.

If the badge is set to 0 it will always get removed from the message sent to FCM...

I really hope we can get a fix for this.

**Comment by brozot** [comment] 2019-08-12 16:41
Hi sorry for this very late answer :(

This issue should have been fixed in the Version 1.2.6

**Closed by brozot** 2019-08-12 16:41 UTC
