### ISSUE TITLE
Laravel-FCM.INFO: notification send to 3 devices success: 0 failures: 3 number of modified token : 0

### ISSUE THREAD

**Issue by umairali** [brozot/Laravel-FCM#23] opened 2016-12-26 11:37 UTC
I m trying to send notifications but I am receiving this error.

Laravel-FCM.INFO: notification send to 3 devices success: 0 failures: 3 number of modified token : 0

I am using (**Sending a Downstream Message to Multiple Devices**) code

**Comment by brozot** [comment] 2016-12-27 21:02
Hello, 

Are you sure that you have correctly registered tokens provided by your client app ?
Have you tried to sent a notification with your token from the FCM console

**Comment by umairali** [comment] 2016-12-28 05:40
Yes, I tried but I don't know why some tokens are not working and I received this message.

**Comment by rslhdyt** [comment] 2017-03-04 02:34
It work's.

the problem is Firebase client for web (javascript), cannot receive notification with message payload
badge and sound. according to https://firebase.google.com/docs/cloud-messaging/http-server-ref.

working sample for notification to web.

`$notificationBuilder = new PayloadNotificationBuilder();
        $notificationBuilder->setTitle('title')
            ->setBody('body')
            ->setClickAction('http://localhost:8081');

        $notification = $notificationBuilder->build();`

Thank You @brozot for Great Package

**Comment by shinnlu** [comment] 2017-03-07 07:29
i have the same problem with same code (Sending a Downstream Message to Multiple Devices)
Laravel-FCM.INFO: notification send to 1 devices success: 0 failures: 1 number of modified token : 0 
my client is android app, please help me to resolve this problem.

**Comment by shinnlu** [comment] 2017-03-07 08:00
i found the problem
when i get tokens from database with code:

`$tokens = Subscribe::select('device_token')
			->whereIn('UserID', $users)
			->where('type','=','Alert')
			->get();`


it's return two dimension array like this:
`Array
(
    [0] => Array
        (
            [device_token] => TOKEN1
        )
    [1] => Array
        (
            [device_token] => TOKEN2
        )
)`
it's wrong, the tokens array should be one dimension array like this:
`Array
(
    [0] => TOKEN1
    [1] => TOKEN2
)`

**Comment by brozot** [comment] 2017-03-10 20:12
@shinnlu Is it solve for you ?  can I close the issue ?

**Comment by shinnlu** [comment] 2017-03-11 01:20
sure, thanks.

**Closed** 2017-03-11 05:23 UTC
Labels: help wanted
